### ISSUE TITLE
what is the login_token meaning

### ISSUE THREAD

**Issue by 25Jason2017** [SeaLoong/HbookerCrawler#1]
I can not input my password or id , it seems that they are all wrong answer
Besides，the first time I use it after input my wrong account form, the program occur a error shows 'latin-1' codec can't encode characters in position 12-13: ordinal not in range#256#.Did I use the wrong mthod?

**Comment by SeaLoong** [comment]
Are you a Chinese?(我觉得只有国人会用这玩意吧，没想到除了自己之外还会有人用)
"login_token"和"reader_id"是网页Cookie项，获取方法：在网页登录帐号后，在任意页面打开 开发人员工具(F12)，选择 网络(Network)，刷新网页(F5)，查看数据包并记录有关Cookies(login_token，reader_id)，然后将记录的Cookies输入程序使用（操作图我会在readme中贴出）。
如果不需要登录却不小心输入了无效的Cookies，可通过删除 ../books/hbookercrawler.cfg 文件恢复使用。

**Comment by 25Jason2017** [comment]
当然是啊，由于准备结束c++开始java学习，就打算学习一波我用的网页爬虫看看，没想到这里真的有
